### PR TITLE
feat: add vuepress docs site

### PR DESCRIPTION
**Pull request by sadn1ck**
Signed-off-by: Anik Das <anikdas0811@gmail.com>

## Description
- adds VuePress documentation for Vocabulary Components
image

## Issues
- nothing loads now, to see the basic structure (sidebar and all), comment out [this line](https://github.com/sadn1ck/vocabulary-components/blob/feat/docs-vuepress/docs/.vuepress/enhanceApp.js#L4) of code
- currently facing an issue where the components imported into the vuepress instance cannot resolve the `@/mixins/*` path from the original library path

image

cc: @MuluhGodson @brylie 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by brylie** [comment]
This is looking good so far.

**Review by brylie — CHANGES_REQUESTED** [review]
Be careful to ensure that we give credit to other contributors to this project by adding "co-authored by: ..." to commits where we are copying code. For example, we are losing the commit history to DonateButton.vue, so it would be good to give credit to the other contributors of that component in the commit message.

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by sadn1ck** [comment]
Thanks, I was unaware about this. Would it be okay to have a single final commit mentioning all co-authors, or should I be mentioning those in every commit? 

Also I haven't changed the components (ie, DonateButton.vue) apart from adding extension to imports, so we won't be losing its commit history. 

The only thing removed are the stories, which are being replaced with the new custom components with the copied code, I believe you mean those?

**Comment by brylie** [comment]
For now, just add the missing contributors in a subsequent commit. If any other components copy over, just mention the co-authors in the initial commit. There shouldn't be too many contributors to add, and each contributor only needs to be cited at least once for attribution.

**Comment by sadn1ck** [comment]
Alright, I'll make sure to add them. Thanks for the heads up!

**Comment by sadn1ck** [comment]
## Update!

- Added most components
- Setup a [deployment](https://pr-20-vocab-comp.netlify.app/) on Netlify
- Added site title, and code to every component page
- Back to top official plugin added, just in case we need it later


### Things to note
- VLocale component is not finished it seems, even in the lib source

### [Deployment](https://pr-20-vocab-comp.netlify.app/)

cc: @brylie @MuluhGodson @shailee-m 

Please leave any feedback you might have, thanks!

**Comment by brylie** [comment]
It looks great!

**Comment by sadn1ck** [comment]
@brylie I think I can un-draft (?) this for wider review now, there isn't much left to add apart from text content, I feel, which we can gradually add back.

**Review by brylie — APPROVED** [review]

**Pull request merged**
